// src/errors/error-code.ts
export enum ErrorCode {
    // Authentication errors
    UNAUTHORIZED = 'UNAUTHORIZED',
    INVALID_TOKEN = 'INVALID_TOKEN',
    MISSING_TOKEN = 'MISSING_TOKEN',
    EXPIRED_TOKEN = 'EXPIRED_TOKEN',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    ALREADY_AUTHENTICATED = 'ALREADY_AUTHENTICATED',
    GOOGLE_AUTH_FAILED = 'GOOGLE_AUTH_FAILED',
    INVALID_STATE = 'INVALID_STATE',
  
    // Authorization errors
    FORBIDDEN = 'FORBIDDEN',
  
    // Resource errors
    NOT_FOUND = 'NOT_FOUND',
    ALREADY_EXISTS = 'ALREADY_EXISTS',
  
    // Validation errors
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    MISSING_FIELDS = 'MISSING_FIELDS',
    INVALID_FORMAT = 'INVALID_FORMAT',
  
    // Server errors
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
  
    // Other errors
    BAD_REQUEST = 'BAD_REQUEST',
    CONFLICT = 'CONFLICT',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  }
  